CREATE TABLESPACE TABLESPACE_DEVELOPER DATAFILE 'tableSpace_Developer.dbf' SIZE 1M AUTOEXTEND ON;
CREATE USER DEVELOPER IDENTIFIED BY Poolmejor000;

ALTER  USER DEVELOPER
DEFAULT   TABLESPACE TABLESPACE_DEVELOPER
QUOTA UNLIMITED ON   TABLESPACE_DEVELOPER;

GRANT CREATE SESSION    TO DEVELOPER;
GRANT CREATE PROCEDURE  TO DEVELOPER;
GRANT CREATE TABLE      TO DEVELOPER;
GRANT CREATE SEQUENCE   TO DEVELOPER;
GRANT CREATE TRIGGER    TO DEVELOPER;
GRANT CREATE VIEW       TO DEVELOPER;
GRANT CREATE JOB        TO DEVELOPER;

GRANT CREATE ANY TRIGGER TO DEVELOPER;
--GRANT EXECUTE ON DBMS_SCHEDULER TO DEVELOPER;